# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=2048)),
                ('image_url', models.TextField(null=True)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
