# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
