version: '2'
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: bash -c "gunicorn pynews.wsgi:application -w 2 -b 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./docker/crontab:/etc/crontab
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/django.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./docker/nginx/client.conf:/etc/nginx/conf.d/default.conf
