version: '2'
services:
  django:
    build: .
    command: bash -c "gunicorn pynews.wsgi:application -w 2 -b 0.0.0.0:8000"
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes_from:
      - django
    volumes:
      - ./docker/nginx/django.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
  client:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/nginx/client.conf:/etc/nginx/conf.d/default.conf
      - ./src/client/build:/var/www/html
