# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170801_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
